version: "3.7"

services:
  frontend:
    build:
      context: .
      dockerfile: ./frontend/Dockerfile
      args:
        PORT: 3000
    environment:
      - PORT=5173
    ports:
      - "5173:5173"
    depends_on:
      - backend
    networks:
      - app-network

  backend:
    build:
      context: .
      dockerfile: ./backend/Dockerfile
      args:
        PORT: 3000
    environment:
      - PORT=3000
    ports:
      - "3000:3000"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge